// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADV7zsQwTpK3meuNgBYbnKdd4reqyRPiI',
    appId: '1:305847163657:web:630700682c1348875ed1d8',
    messagingSenderId: '305847163657',
    projectId: 'todolist-2d15c',
    authDomain: 'todolist-2d15c.firebaseapp.com',
    storageBucket: 'todolist-2d15c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8FZyNTGuUoN88YBB2PjRCNFdzItQKaTQ',
    appId: '1:305847163657:android:be3a5d5efc9c4b335ed1d8',
    messagingSenderId: '305847163657',
    projectId: 'todolist-2d15c',
    storageBucket: 'todolist-2d15c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfoGzVKYarnQEBs-qfuPli0OUjnAsraM',
    appId: '1:305847163657:ios:63b304ad64f453a55ed1d8',
    messagingSenderId: '305847163657',
    projectId: 'todolist-2d15c',
    storageBucket: 'todolist-2d15c.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqfoGzVKYarnQEBs-qfuPli0OUjnAsraM',
    appId: '1:305847163657:ios:63b304ad64f453a55ed1d8',
    messagingSenderId: '305847163657',
    projectId: 'todolist-2d15c',
    storageBucket: 'todolist-2d15c.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADV7zsQwTpK3meuNgBYbnKdd4reqyRPiI',
    appId: '1:305847163657:web:dbd7a56c209ff6495ed1d8',
    messagingSenderId: '305847163657',
    projectId: 'todolist-2d15c',
    authDomain: 'todolist-2d15c.firebaseapp.com',
    storageBucket: 'todolist-2d15c.firebasestorage.app',
  );
}
